[package]
name = "fluxcapacitor-ebpf"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya-ebpf = "0.1.0"
aya-log-ebpf = "0.1.0"

[[bin]]
name = "fluxcapacitor"
path = "src/main.rs"
